services:
  - type: web
    name: predihealth-api
    runtime: python-3.11
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app"
    repo: https://github.com/Kashyapdivakaruni/Efos-final
    region: oregon
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: https://predihealth-frontend.vercel.app
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: static_site
    name: predihealth-frontend
    staticPublishPath: frontend/dist
    buildCommand: "cd frontend && npm install && npm run build"
    repo: https://github.com/Kashyapdivakaruni/Efos-final
    envVars:
      - key: VITE_API_URL
        value: https://predihealth-api.onrender.com/api
